### ISSUE TITLE
Bug: npm run dev on Windows results in Error: spawn next ENOENT

### ISSUE THREAD

**Issue by bobbingwide** [wpengine/faustjs#1144] opened 2022-11-11 12:57 UTC
In my Windows development environment
-  I installed the latest version of Faust using the example command `npx create-next-app` etc.
-  changed directory to my new app
-  then I copied .env.local.sample to .env.local 
-  then ran `npm run dev`

I got the following error.

```
> @faustwp/getting-started-example@0.1.0 dev C:\apache\htdocs\johann
> faust dev

Faust - warn - Could not find FAUSTWP_SECRET_KEY environment variable.
Faust - warn - Some functionality may be limited.
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn next ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn next',
  path: 'next',
  spawnargs: [ 'dev' ]
}
```

I spent a while attempting to resolve this problem by installing next globally.
Eventually I found a hint to resolving the problem in https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

I have implemented a local workaround by changing the `spawn( 'next' )`, adding the `shell:true` args.

line 84 of `node_modules\@faustwp\cli\dist\index.js`
```
 spawn('next', getCliArgs(), { stdio: 'inherit', shell: true });
```

## Applicable Versions

- `@faustwp/core` version: 0.1.3
- `@faustwp/cli` version: 0.1.4

## Steps To Reproduce

On a Windows machine
1. Create a new app called johann
```
C:\apache\htdocs>npx create-next-app -e https://github.com/wpengine/faustjs/tree/main --example-path examples/next/faustwp-getting-started --use-npm
npx: installed 1 in 2.519s
√ What is your project named? ... johann
Creating a new Next.js app in C:\apache\htdocs\johann.
```
2. cd to johann
3. copy `.env.local.sample` to `.env.local`
4. run `npm run dev`

## The current behavior

```
C:\apache\htdocs\johann>npm run dev

> @faustwp/getting-started-example@0.1.0 dev C:\apache\htdocs\johann
> faust dev

Faust - warn - Could not find FAUSTWP_SECRET_KEY environment variable.
Faust - warn - Some functionality may be limited.
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn next ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn next',
  path: 'next',
  spawnargs: [ 'dev' ]
}
```

## The expected behavior
No errors. The code connects to the Faust Example Site and does its stuff.  

```
C:\apache\htdocs\johann>npm run dev

> @faustwp/getting-started-example@0.1.0 dev C:\apache\htdocs\johann
> faust dev

Faust - warn - Could not find FAUSTWP_SECRET_KEY environment variable.
Faust - warn - Some functionality may be limited.
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\apache\htdocs\johann\.env.local
event - compiled client and server successfully in 1985 ms (800 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 227 ms (801 modules)
{
  Node: [
    'Category',           'EnqueuedScript',
    'EnqueuedStylesheet', 'ContentType',
    'Taxonomy',           'User',
    'Comment',            'MediaItem',
    'Page',               'Post',
    'PostFormat',         'Tag',
    'Project',            'UserRole',
    'Testimonial',        'Menu',
    'MenuItem',           'Plugin',
    'Theme',              'CommentAuthor'
  ],
...
```

and can be visited at http://localhost:3000

![image](https://user-images.githubusercontent.com/2474435/201345034-455e9cea-5ad4-4a0d-aaac-6975ffe35598.png)

**Comment by theodesp** [comment] 2022-11-21 10:37
Hey @bobbingwide thanks for the report. We will need to reproduce this but it might take more time as we don't have access to Windows machines. Might try a VM.

**Comment by Ahrary** [comment] 2022-12-18 10:36
Server won't start on Windows 11 PC.

C:\www\frontend> `npm run dev`

```
> frontend@0.1.0 dev
> faust dev
```
nothing further...

```
{
  "name": "frontend",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "faust dev",
    "build": "faust build",
    "generate": "faust generatePossibleTypes",
    "start": "faust start"
  },
  "dependencies": {
    "@apollo/client": "^3.6.6",
    "@faustwp/cli": "0.2.0",
    "@faustwp/core": "0.2.0",
    "@wordpress/base-styles": "^4.7.0",
    "@wordpress/block-library": "^7.13.0",
    "classnames": "^2.3.1",
    "graphql": "^16.6.0",
    "next": "^12.1.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sass": "^1.54.9"
  }
}
```

**Comment by josephfusco** [comment] 2023-01-03 16:35
Hi @bobbingwide & @Ahrary, thanks for reporting this issue with Windows environments.
We've created a ticket ([MERL-689](https://wpengine.atlassian.net/browse/MERL-689)) in our internal backlog to investigate this and will write back when we have more details.

**Comment by szaleq** [comment] 2023-01-04 09:44
I have the same issue on Windows 10. The problem is a `spawnSync` command, which requires the `.cmd` suffix for windows commands. If I change the line `71` in `@faustwp/cli/dist/index.js` to add the `.cmd` suffix, everything works fine.
```javascript
// Before:
    process.exit((_a = spawnSync('next', getCliArgs(), { stdio: 'inherit', encoding: 'utf8' })) === null || _a === void 0 ? void 0 : _a.status);

// After:
    process.exit((_a = spawnSync('next.cmd', getCliArgs(), { stdio: 'inherit', encoding: 'utf8' })) === null || _a === void 0 ? void 0 : _a.status);
```

You should consider using [cross-spawn](https://www.npmjs.com/package/cross-spawn) which is a cross platform solution instead of `spawnSync` which behaves differently depending on the environment.

**Comment by marziolek** [comment] 2023-01-12 15:11
> Server won't start on Windows 11 PC.
> 
> C:\www\frontend> `npm run dev`
> 
> ```
> > frontend@0.1.0 dev
> > faust dev
> ```
> 
> nothing further...
> 
> ```
> {
>   "name": "frontend",
>   "private": true,
>   "version": "0.1.0",
>   "scripts": {
>     "dev": "faust dev",
>     "build": "faust build",
>     "generate": "faust generatePossibleTypes",
>     "start": "faust start"
>   },
>   "dependencies": {
>     "@apollo/client": "^3.6.6",
>     "@faustwp/cli": "0.2.0",
>     "@faustwp/core": "0.2.0",
>     "@wordpress/base-styles": "^4.7.0",
>     "@wordpress/block-library": "^7.13.0",
>     "classnames": "^2.3.1",
>     "graphql": "^16.6.0",
>     "next": "^12.1.6",
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2",
>     "sass": "^1.54.9"
>   }
> }
> ```

Same for me. I can't even try if faust is the way to go 😢

**Comment by josephfusco** [comment] 2023-01-25 20:09
The fix for this issue has been merged into this project's canary branch, with release early next week.

Props to @szaleq on the discovering the `.cmd` issue!

**Comment by blakewilson** [comment] 2023-04-06 14:42
Closing as this has been released for some time now

**Closed by blakewilson** 2023-04-06 14:42 UTC
Labels: help wanted, has jira, package: @faustwp/cli
