### ISSUE TITLE
Bug: nodeByUri return null in category page

### ISSUE THREAD

**Issue by idmahbub** [wpengine/faustjs#1613] opened 2023-10-17 12:07 UTC
## Applicable Versions
- "graphql": "^16.6.0",
-  "@apollo/client": "^3.6.6"
- "@faustwp/cli": "1.1.1"
- "@faustwp/core": "1.1.2"
- WordPress version: 6.3

## Captured
<img width="1041" alt="Screen Shot 2023-10-17 at 19 00 12" src="https://github.com/wpengine/faustjs/assets/2823242/86673365-cfa4-4304-9fab-2d14a98390f1">

**Comment by blakewilson** [comment] 2023-10-17 12:33
Hi @idmahbub, 

Thanks for opening an issue.

Have you verified the query and variables you used in your Faust Template don't return null in the WPGraphQL GraphiQL in the WP Admin? We'll want to rule this out before we can confirm this is a Faust specific issue.


Can you please also paste the query and variables you used in your Faust template? I could test it out locally as well.

**Comment by arnautg** [comment] 2023-10-17 18:13
This is caused by the new update of the wp-graphql `v1.17.0` downgrading to the `v1.16.0` solves the issue, the problem is that the URI that is passed by parameter is now the full the path `http://localhost:3000/category/news/` when previously was `/category/news` if you run in the GraphQL IDE the following query 
```query GetNodeByUri($uri: String!) {
  nodeByUri(uri: $uri) {
    __typename
  }
}```


Using the full path results into a Post (specifically the latest post of the category)
```
{
  "uri": "/category/noticias/"
}
```

Meanwhile if you run it with this variable results in the category
```
{
  "uri": "/category/noticias/"
}
```

Another temporary fix is to change the `Component.variables` into this:
```Component.variables = ({ uri }) => {
  return {
    uri: new URL(uri).pathname,
    headerLocation: MENUS.PRIMARY_LOCATION,
  };
};```

Not sure which side should fix it

**Comment by blakewilson** [comment] 2023-10-17 18:40
This could also be related to this comment: https://github.com/wp-graphql/wp-graphql/pull/2341#issuecomment-1128719980

**Comment by jasonbahl** [comment] 2023-10-17 18:44
@josephfusco and I are working on reproducing right now. 👀

**Comment by josephfusco** [comment] 2023-10-17 19:01
Hey @idmahbub can you please provide the [Faust.js WordPress Plugin](https://wordpress.org/plugins/faustwp/) version you are using? Thank you!

**Comment by idmahbub** [comment] 2023-10-18 05:45
> This is caused by the new update of the wp-graphql `v1.17.0` downgrading to the `v1.16.0` solves the issue, the problem is that the URI that is passed by parameter is now the full path `http://localhost:3000/category/news/` when previously was `/category/news` if you run in the GraphQL IDE the following query
> 
> ```
> query GetNodeByUri($uri: String!) {
>   nodeByUri(uri: $uri) {
>     __typename
>   }
> }
> ```
> 
> Using the full path results into a Post (specifically the latest post of the category)
> 
> ```
> {
>   "uri": "http://localhost:3000/category/news"
> }
> ```
> 
> Meanwhile, if you run it with this variable results in the category
> 
> ```
> {
>   "uri": "/category/news/"
> }
> ```
> 
> Another temporary fix is to change the `Component.variables` into this:
> 
> ```
> Component.variables = ({ uri }) => {
>   return {
>     ...
>     uri: new URL(uri).pathname,
>     ...
>   };
> };
> ```
> 
> Not sure which side should fix it, FaustJS or [wp-graphql](https://github.com/wp-graphql/wp-graphql)

can be run by changing the uri value `uri: new URL(uri).pathname` , but coming 2 warning in console now 
<img width="1096" alt="Screen Shot 2023-10-18 at 12 42 58" src="https://github.com/wpengine/faustjs/assets/2823242/e00de521-c364-4660-b048-706ee43d958c">

**Comment by idmahbub** [comment] 2023-10-18 05:48
> Hey @idmahbub can you please provide the [Faust.js WordPress Plugin](https://wordpress.org/plugins/faustwp/) version you are using and which settings you have toggled on? Thank you!

faust plugin versin in Version 6.3.2, an this the setup for me
<img width="815" alt="Screen Shot 2023-10-18 at 12 47 41" src="https://github.com/wpengine/faustjs/assets/2823242/b062f4d3-fca4-46f0-ad17-402f38b16fbf">

**Comment by jasonbahl** [comment] 2023-10-18 18:49
I think this callback that replaces term links needs to be updated: https://github.com/wpengine/faustjs/blob/canary/plugins/faustwp/includes/replacement/callbacks.php#L213-L227

The `post_link` callback, [right above it](https://github.com/wpengine/faustjs/blob/canary/plugins/faustwp/includes/replacement/callbacks.php#L203-L206), has the following qualifier: 

```php
if (
		! is_rewrites_enabled()
		|| ( function_exists( 'is_graphql_request' ) && is_graphql_request() )
	) {
```

I believe the `term_link` callback also needs the same qualifier. 

If it is a graphql request, return the link as-is instead of making it an absolute link.

**Comment by jasonbahl** [comment] 2023-10-18 19:48
I've opened this PR #1616 which I believe should resolve this issue.

**Comment by josephfusco** [comment] 2024-01-08 19:41
Reopening this as a fix has not yet been merged https://github.com/wpengine/faustjs/pull/1653

**Closed** 2024-01-10 14:13 UTC
