### ISSUE TITLE
FAUSTJS PLUGIN GIVING ERRROS AND SLOWING DOWN WEBSITE

### ISSUE THREAD

**Issue by esilverman682** [wpengine/faustjs#809] opened 2022-03-14 12:41 UTC
- GETTING ERROR ON ACF PRO PAGE FROM FAUSTJS PLUGIN (ERROR SEEEN BELOW)
- WORDPRESS TRIES TO LOAD LONG PERIODS OF TIME (MEMORY & RAM IS HIGH / CPU IS HIGH/ PHP 8 / PHP MEMORY HIGH -512MB)
- EVENTUALLY LOADS AFTER LONG WAIT TIME AND EVERYTHING THEREAFTER  IS FAST AND ACCESSIBLE

USING:
- FAUSTJS PLUGIN
- HEADLESS WORDPRESS
- ACF PRO
- CPTUI

ERROR: 
Warning: Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wp-content/plugins/faustwp/includes/replacement/callbacks.php on line 151

**Comment by theodesp** [comment] 2022-03-14 13:19
Hello @esilverman682. This is a duplicate of 
https://github.com/wpengine/faustjs/issues/752

Would you mind if you provide a reproduction steps or a repo as I'm not able to verify this issue when using AFC pro?

Kind regards

**Comment by theodesp** [comment] 2022-03-14 14:09
@esilverman682 I've managed to reproduce this in PHP 8.0. Will post you updates here.

**Comment by esilverman682** [comment] 2022-03-14 14:50
I can add you to the wordpress instance & include you on the repo. What is
your github email / username? And please provide your email if you need to
look a the Wordpress instance.

Thank you.

**Comment by esilverman682** [comment] 2022-03-15 17:59
I like the faust plugin but will need to abandon it if there isn't a fix
for this error since it slows down the backend WP performance level. Have
you been able to resolve this issue

**Comment by esilverman682** [comment] 2022-03-15 20:41
Thank you for the reply. 

1. Can you provide an estimated timeframe when the new FaustWP release will be?
2. Has this error affected WP performance on your end as well?

Your response will help us on our timelines for this project and is much appreciated.

**Comment by theodesp** [comment] 2022-03-16 09:22
Hello @esilverman682. I hope you are doing well. In regards to your questions:

1. We don't have a definite answer to that. However we do have an average release cadence of 2 weeks and an engineer has already been working on providing a fix for this issue.

2. I wasn't able to verify the WP Perfomance issue and I would like to ask some questions to clarify some assumptions: 
    * Is this happening on a brand new WP install?
    * How many posts and CPTs you have on that install?
    * Is this issue happening when you build the Faust.js frontend for production or during development?
    * Is the WP instance that loads slowly or the Headless Frontend?
    
Kind regards

**Comment by esilverman682** [comment] 2022-03-16 15:44
1.

   We don't have a definite answer to that. However we do have an average
   release cadence of 2 weeks and an engineer has already been working on
   providing a fix for this issue. --> Ok thanks.
   2.

   I wasn't able to verify the WP Perfomance issue and I would like to ask
   some questions to clarify some assumptions:
   - Is this happening on a brand new WP install? -->YES
      - How many posts and CPTs you have on that install? --> 9 (Same as I
      have been using for 4 years with no issues)
      - Is this issue happening when you build the Faust.js frontend for
      production or during development?  (both - we are generating pushes to
      Vercel after developer commits )
      - Is the WP instance that loads slowly or the Headless
      Frontend?(It produces a 524 Cloudflare and only happening on the backend
      not affecting the frontend )

**Comment by wrivkap** [comment] 2022-03-25 19:16
Hi Im wondering if there is any update for this issue. I have updated the plugin. Im using ACF Pro and I wiped the Fields clean totally empty. and the error still appears when creating a new custom field. Warning: Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wp-content/plugins/faustwp/includes/replacement/callbacks.php on line 151

**Comment by esilverman682** [comment] 2022-03-25 19:18
Hi Im wondering if there is any update for this issue. I have updated the plugin. Im using ACF Pro and I wiped the Fields clean totally empty. and the error still appears when creating a new custom field. Warning: Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wp-content/plugins/faustwp/includes/replacement/callbacks.php on line 151

**Comment by theodesp** [comment] 2022-03-28 13:46
@esilverman682 We will be releasing a new version of the FaustWP Plugin tomorrow:

Fixes a PHP 8 warning that occurred on post types not registered with WP GraphQL [#812](https://github.com/wpengine/faustjs/pull/812)

**Comment by esilverman682** [comment] 2022-03-28 19:56
Thank you Theofanis.

**Comment by blakewilson** [comment] 2022-04-05 15:44
Hi @esilverman682, this fix should now be in [faustwp@0.7.7](https://wordpress.org/plugins/faustwp/#developers). If you still experience this issue after updating, please open a new ticket. Thanks!

**Closed by blakewilson** 2022-04-05 15:44 UTC
Labels: bug, duplicate
