### ISSUE TITLE
Bug: Logging out (via toolbar) on a preview route should not automatically log back in

### ISSUE THREAD

**Issue by blakewilson** [wpengine/faustjs#1778] opened 2024-02-01 15:28 UTC
## Environment
- `@faustwp/core` version: 2.0.0
- `@faustwp/cli` version: 2.0.0
- `@faustwp/blocks` version: N/A
- `@faustwp/block-editor-utils` version: N/A
- WordPress version: 6.4.3
- Browser, OS, and other relevant software versions:

## Description

When on a preview route, logging out via the toolbar will successfully log you out, but since you are on a preview URL, you will be automatically logged back in. This should not happen, let's redirect the user to the homepage or something similar.

## Steps to Reproduce
1. Preview a headless post
2. Click the logout button in the toolbar
3. See that you are still logged in

## Expected vs. Actual Behavior
Expected: You are logged out when hitting "logout" in the toolbar
Actual behavior: You are still logged in after hitting "logout" from the toolbar

**Comment by ChrisWiegman** [comment] 2024-03-05 16:15
Closing as this is a duplicate of #1812

**Closed by ChrisWiegman** 2024-03-05 16:15 UTC
Labels: bug
