### ISSUE TITLE
Bug: getApolloAuthClient function not working correctly when usePersistedQueries is enabled and using PersistedQueriesPlugin

### ISSUE THREAD

**Issue by tuanfront-end** [wpengine/faustjs#1540] opened 2023-08-21 15:49 UTC
Wishing everyone a good day. The problem I'm having is that it seems that `getApolloAuthClient()` is not working correctly when I enable `usePersistedQueries: true` in the config file and use the `PersistedQueriesPlugin` plugin (https://github.com/wp-graphql/wpgraphql.com/blob/master/src/plugins/PersistedQueriesPlugin.js).

I got error `414` when my query seems long, then I enabled `usePersistedQueries: true` but it didn't work, I searched and used the `PersistedQueriesPlugin` plugin. After that, the 414 error went away, but the problem was that the queries that needed to authenticate the client `getApolloAuthClient()` returned `null`.

## Steps To Reproduce
I tried again with a new Faustjs project and the problem still occurs.
1. Initialize new faustjs project
2. Configure to WordPress site and write 1 simple query `getViewer`, `getApolloAuthClient` works fine and `getViewer` returns data as expected.
3. Enable `usePersistedQueries: true` in the file faust.config and create a `PersistedQueriesPlugin` plugin using this code - https://github.com/wp-graphql/wpgraphql.com/blob/master/src/plugins/PersistedQueriesPlugin.js
4. Recheck the `getViewer` query returns `null`, while `isAuthenticated` still is true.
## The current behavior
The `getViewer` query returns `null`, while `isAuthenticated` still is true

## The expected behavior
The `getViewer` query must returns viewer data correctly when `isAuthenticated` is true.

**Comment by tuanfront-end** [comment] 2023-08-21 15:53
@theodesp @jasonbahl  Would be very grateful for any great help from you guys. Thanks in advance

**Comment by blakewilson** [comment] 2023-08-21 16:39
Hi @tuanfront-end, thank you for your issue!

With the `usePersistedQueries` option set to `true`, no plugin is required to enable persisted queries. I believe @jasonbahl was using that plugin as that was the only way to enable persisted queries before we introduced the `usePersistedQueries` flag.

I created an example project with persisted queries enabled while fetching authenticated content with `getApolloAuthClient` and was able to get the proper data back:

<img width="1106" alt="Screenshot 2023-08-21 at 11 38 17 AM" src="https://github.com/wpengine/faustjs/assets/5946219/efb4c93e-9a98-4918-b55a-d3716718956e">

You can check that public repo out here:

https://github.com/blakewilson/faust-auth-persisted-queries

Additionally, here is the specific commit with those changes (I cloned the Faust example project; this commit contains the only changes from the example):

https://github.com/blakewilson/faust-auth-persisted-queries/commit/ee0edffe8ac2e5d04f6befb9bc96f7a0cbdc4522

If you are still experiencing this issue, could you please create a reproducible repo that we can use to debug? Thanks!

**Comment by blakewilson** [comment] 2023-08-25 00:52
Hi @tuanfront-end,

We may have uncovered a bug relating to persisted queries and I'm curious if it's related to what you are experiencing here.

Could you try running the latest nightly Faust build and see if it fixes the issue you are seeing?

You can do so by running:

```bash
npm install @faustwp/core@canary
```

**Comment by tuanfront-end** [comment] 2023-08-25 00:55
Thank you so much @blakewilson, I am going to check it out right now.

**Comment by MattOndo** [comment] 2023-08-27 02:41
Hey there! I'm experience the same exact issue. After installing `@faustwp/core@canary` the issue seems to be resolved. I do still occasionally get this error though:

ApolloError: Persisted queries are not supported by this server

I've heard conflicting info on whether WPGraphQL Smart Cache, so have been enabling/disabling that plugin to see if that's causing the error but doesn't seem to matter. As of right now, the plugin is installed & activated and am seeing this error message.

**Comment by blakewilson** [comment] 2023-08-31 14:40
Hey @tuanfront-end, were you able to confirm if this canary release fixed the issue you were seeing?

**Comment by blakewilson** [comment] 2023-08-31 14:42
@MattOndo Glad to see the issue you were facing seems to have been resolved!

As for the `ApolloError: Persisted queries are not supported by this server` error message, from my understanding, you'll only see that when you don't have [WPGraphQL Smart Cache](https://wordpress.org/plugins/wpgraphql-smart-cache/) enabled.

So if you do have the plugin enabled and are still seeing this, could you please open a new issue with steps to reproduce?

**Comment by tuanfront-end** [comment] 2023-09-01 02:02
@blakewilson  I'm very sorry that I wanted to check further with the queries so I didn't respond right away.
So far everything seems to be working fine. 
Thank you so much for your work 🩷

**Comment by mindctrl** [comment] 2024-01-16 20:06
It looks like everything was resolved here. 🎉  I'm going to close the issue. If you're still experiencing issues, feel free to re-open.

**Closed by mindctrl** 2024-01-16 20:06 UTC
Labels: awaiting response
