### ISSUE TITLE
Bug: App Router - Unexpected errors from auth server actions (onLogin and onLogout)

### ISSUE THREAD

**Issue by MattOndo** [wpengine/faustjs#1702] opened 2024-01-02 19:07 UTC
## Environment
- `@faustwp/core` version: latest & canary
- `@faustwp/cli` version: latest & canary
- `@faustwp/blocks` version: n/a
- `@faustwp/block-editor-utils` version: n/a
- WordPress version: 6.4.2
- Browser, OS, and other relevant software versions: All browsers, and OS', but building on macOS Sonoma latest

## Description
**Issue 1: onLogin not executing / returning undefined**

When attempting to login, the following error is displayed in browser & server logs:

```
Unhandled Runtime Error
Error: Cannot read properties of undefined (reading 'error')

Source
src/app/login/action.ts (10:10) @ error

   8 | 
   9 | console.log('=== loginAction ===', res);
> 10 | if (res.error) {
     |        ^
  11 |   return res;
  12 | }
  13 |
```

As you can see in this example code, I am attempting to log `res` to the console. At this point, `res` is `undefined`.

After investigating and troubleshooting, I realized the onSubmit() function in `@faustwp/experimental-app-router/dist/server-actions/loginAction.js` was not being executed at all. Confirmed by adding `console.log('loginAction', formData)` directly within this function which does not execute:

```javascript
export async function onLogin(formData) {
  'use server';
  console.log('loginAction', formData);
  try {
    ...
```

Poking around, I found by commenting out the [`'use server';` line in this file](https://github.com/wpengine/faustjs/blob/205fb09ee09eb2a25ed284324d76391a63d9d7b6/packages/experimental-app-router/src/server-actions/loginAction.ts#L49) "fixed" the issue - no longer getting `undefined` when calling onSubmit(), and allowing the user to authenticate/login.

**Issue 2: Passing function in attribute on logout form & the onLogout() function**

Once issue 1 was resolved, this browser error message displays upon logging in. This error displays on any page where the logout form is included:

```
Unhandled Runtime Error
Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
  <form action={function} children=...>
               ^^^^^^^^^^
```

This occurs with the [provided logout form](https://github.com/wpengine/faustjs/blob/205fb09ee09eb2a25ed284324d76391a63d9d7b6/examples/next/app-router/app/my-account/page.tsx#L39), as well as when the logout form is abstracted into its own component.

Again, poking around and testing things, I found by moving the [`'use server';` line](https://github.com/wpengine/faustjs/blob/205fb09ee09eb2a25ed284324d76391a63d9d7b6/packages/experimental-app-router/src/server-actions/logoutAction.ts#L5) from within the `@faustwp/experimental-app-router/dist/server-actions/logoutAction.js` onLogout() function to the top of the file resolved the issue.

## Steps to Reproduce
1. Follow setup instructions outlined in the [faustjs.org Getting Started with the Experimental App Router](https://faustjs.org/tutorial/getting-started-with-the-experimental-app-router)
2. Attempt to login (this is where the first issue arises)
3. Comment out or remove line 49 of `/node_modules/@faustwp/experimental-app-router/dist/server-actions/loginAction.js`
4. Stop server, delete .next directory, start server
5. Attempt to login (login will work, this is where the second issue arises)
6. Move line 4 of `/node_modules/@faustwp/experimental-app-router/dist/server-actions/logoutAction.js` to be the first line
7. Stop server, delte .next directory, start server
8. You should already be logged in, depending on cookies/etc you may need to log in again. At this point no more issues logging in or logging out.

## Expected vs. Actual Behavior
Unexpected errors during login procedure, and subsequent issues.

## Reproducible Demo
My code is not in a public repo, but this has been reproduced by myself several times, as well as by members of the FaustJS Discord (thread [here](https://discord.com/channels/836253505944813629/1190895140236165230/1190895140236165230)). However, my example code matches the [app-router example](https://github.com/wpengine/faustjs/tree/canary/examples/next/app-router) exactly.

**Comment by CesarBenavides777** [comment] 2024-01-02 21:29
I am also getting this error! Also previews don't work either

**Comment by nicholaspretorius** [comment] 2024-01-10 13:39
I can confirm that: 

* I am seeing the errors described above 
* The quick-fixes described above work for the meantime, however, are not practical as they will be overwritten once node_modules are updated.
* I have not looked at the previews of drafts yet...

### Suggestion:

I think it would be better to update the Faust App Router example with a better "logout" experience. Issues above to one side for the moment, there is an improvement that could be made: 

* Users typically expect to be _redirected_ to another page when logging out, usually back to the login or home page. 
* We may want to use the Logout button elsewhere. As such, hard-coding the logout functionality to the /my-account page is not very DRY.

In order to take a step towards a better logout experience, I feel it would be better to use the pattern defined in the `login.tsx` page and use the `onLogout` function within an `action` on `my-account`. 

To this end, one could do the following within the /my-account folder: 

1. Create an action.ts file to contain the action
2. Create a logout.tsx file to contain the Logout button
3. Use the above Logout button and action in the my-account page (or elsewhere as a reusable component) rather than use `onLogout` directly within my-account. 

**/my-account/action.ts:**

```
'use server';

import { onLogout } from '@faustwp/experimental-app-router';
import { redirect } from 'next/navigation';

export async function logoutAction() {

    const res = await onLogout();

    // console.log({ res });

    redirect('/login');
}
```

**/my-account/logout.tsx:**

```
'use client';

import { useFormState, useFormStatus } from 'react-dom';
import { logoutAction } from './action';

function LogoutButton() {
    const status = useFormStatus();
    return (
        <button disabled={status.pending}>
            {status.pending ? 'Logging out...' : 'Logout'}
        </button>
    );
}

export default function Logout() {

    const [state, formAction] = useFormState(logoutAction, null);

    return (
        <form action={formAction}>
            <LogoutButton />
        </form>
    );
}
```

**/my-account/page.tsx**

```
import { PleaseLogin } from '@/components/please-login';
import { gql } from '@apollo/client';
import { getAuthClient } from '@faustwp/experimental-app-router';
import Logout from './logout';

export default async function Page() {
  const client = await getAuthClient();

  if (!client) {
    return <PleaseLogin />;
  }

  const { data } = await client.query({
    query: gql`
      query GetViewer {
        viewer {
          name
          posts {
            nodes {
              id
              title
            }
          }
        }
      }
    `,
  });

  return (
    <>
      <h2>Welcome {data.viewer.name}</h2>

      <h3>My Posts</h3>
      <ul>
        {data.viewer.posts.nodes.map((post) => (
          <li key={post.id}>{post.title}</li>
        ))}
      </ul>

      <Logout />
    </>
  );
}

```

While the suggestion above is not DRY either, it has started to separate out the logout functionality from the page itself.

This can be taken a step further by completely removing the `logout.tsx` and `action.ts` buttons from /my-account and put into its own component elsewhere. 

This Faust App Router experiment is looking promising and I look forward to further updates! 🚀 

Thank you for the great work thus far! 🙏

**Comment by blakewilson** [comment] 2024-01-16 16:18
Hey @MattOndo,

Thank you for creating this issue. I've confirmed this behavior and we've moved this bug into our current queue. We will respond soon when we have more details on a fix.

**Comment by MattOndo** [comment] 2024-01-17 18:56
Thank you @blakewilson! Appreciate the support

**Comment by blakewilson** [comment] 2024-01-22 17:12
Hi @MattOndo, what versions of `react`, `react-dom` and `next` are you using? I've just tried using the server actions again on the latest versions of the above packages and I no longer see this issue occurring:

```
"next": "^14.0.1",
"react": "^18.2.0",
"react-dom": "^18.2.0"
```

**Comment by CesarBenavides777** [comment] 2024-01-22 17:24
@blakewilson  just tried with those versions and getting this error:
````
User could not be logged in: Error: Could not fetch tokens
````

The issue seems to be from the token api route

**Comment by blakewilson** [comment] 2024-01-23 21:31
@CesarBenavides777 Is that in prod or on local? I got something similar when I was using LocalWP with `https`, switching back to `http` worked for me.

**Comment by CesarBenavides777** [comment] 2024-01-24 03:55
@blakewilson ah good point. I'm am running local https via `faust dev --experimental-https`. Let me test again on http. Was running on ssl because it's an e-commerce product.

**Comment by blakewilson** [comment] 2024-01-24 05:31
> @blakewilson ah good point. I'm am running local https via `faust dev --experimental-https`. Let me test again on http. Was running on ssl because it's an e-commerce project.

@CesarBenavides777 Please let me know your findings. I was using the same flag, so there may be unworked issues with the '--experimental-https' flag.

**Comment by blakewilson** [comment] 2024-01-24 05:32
@MattOndo were you able to test with the latest versions of next? In my testing it works as expected.

**Comment by nicholaspretorius** [comment] 2024-01-30 09:13
I have tested the example Faust.js app with the following configurations of dependencies according the latest updates on this thread: 

All the react, react-dom and next versions below were tested with the following versions of Faust.js: 
```
"@apollo/experimental-nextjs-app-support": "^0.5.1",
"@faustwp/cli": "^2.0.0",
"@faustwp/core": "^2.1.0",
"@faustwp/experimental-app-router": "^0.2.2",
```

* Tested with both react and react-dom canary versions and the login/logout are working as expected. 
```
"next": "^14.0.1",
"react": "^18.3.0-canary-ce2bc58a9-20231102",
"react-dom": "^18.3.0-canary-ce2bc58a9-20231102"
```

* Tested with both react and react-dom canary and the latest version of Next.js and the login/logout are working as expected. 
```
"next": "^14.1.0",
"react": "^18.3.0-canary-ce2bc58a9-20231102",
"react-dom": "^18.3.0-canary-ce2bc58a9-20231102"
```

* Tested with the latest react and react-dom versions and the login/logout are working as expected. 
```
"next": "^14.0.1",
"react": "^18.2.0",
"react-dom": "^18.2.0"
```

* Tested with the latest Next.js as well as latest react and react-dom and the login/logout are working as expected. 
```
"next": "^14.1.0",
"react": "^18.2.0",
"react-dom": "^18.2.0"
```

**Comment by blakewilson** [comment] 2024-01-30 19:10
> I have tested the example Faust.js app with the following configurations of dependencies according the latest updates on this thread:
> 
> All the react, react-dom and next versions below were tested with the following versions of Faust.js:
> 
> ```
> "@apollo/experimental-nextjs-app-support": "^0.5.1",
> "@faustwp/cli": "^2.0.0",
> "@faustwp/core": "^2.1.0",
> "@faustwp/experimental-app-router": "^0.2.2",
> ```
> 
>  * Tested with both react and react-dom canary versions and the login/logout are working as expected.
> 
> ```
> "next": "^14.0.1",
> "react": "^18.3.0-canary-ce2bc58a9-20231102",
> "react-dom": "^18.3.0-canary-ce2bc58a9-20231102"
> ```
> 
>  * Tested with both react and react-dom canary and the latest version of Next.js and the login/logout are working as expected.
> 
> ```
> "next": "^14.1.0",
> "react": "^18.3.0-canary-ce2bc58a9-20231102",
> "react-dom": "^18.3.0-canary-ce2bc58a9-20231102"
> ```
> 
>  * Tested with the latest react and react-dom versions and the login/logout are working as expected.
> 
> ```
> "next": "^14.0.1",
> "react": "^18.2.0",
> "react-dom": "^18.2.0"
> ```
> 
>  * Tested with the latest Next.js as well as latest react and react-dom and the login/logout are working as expected.
> 
> ```
> "next": "^14.1.0",
> "react": "^18.2.0",
> "react-dom": "^18.2.0"
> ```

@nicholaspretorius Thanks for going through and confirming this behavior with all these different versions! This is super helpful!

**Comment by blakewilson** [comment] 2024-01-30 19:12
@MattOndo It seems like this has been fixed. I'm going to close this issue now but if you are still experiencing problems please feel free to [open a discussion](https://github.com/wpengine/faustjs/discussions/new/choose) or [create a new issue.](https://github.com/wpengine/faustjs/issues/new/choose)

**Closed by blakewilson** 2024-01-30 19:12 UTC
Labels: bug
