### ISSUE TITLE
Bug: ServerSide Rendered Content is sometimes absent from the __NEXT_DATA__ hydration

### ISSUE THREAD

**Issue by jsimondshiebing** [wpengine/faustjs#624] opened 2021-10-28 20:34 UTC
When loading static pages server-side the initial data returned from GQTY requests that utilize the $on notation do not return consistently. There are times where data will be visible from the source as well as in the __NEXT_DATA__ pageProps object, however for the most part blocks return with just the __typename and name properties.

## Applicable Versions

- `@faustjs/core` version: 0.12.4
- `@faustjs/next` version: 0.13.0
- WordPress version: 5.8.1

**Comment by blakewilson** [comment] 2021-10-29 19:01
Thanks for reporting this @jsimondshiebing. I am seeing some inconsistencies with SSG and the `$on` GQty property. I'll do some debugging and report back.

**Comment by blakewilson** [comment] 2021-11-02 05:14
I was able to reproduce this and have a minimal repo demonstrating the issue:

https://github.com/blakewilson/gqty-on-ssg-next-issue/

It seems to be related to GQty, I've opened an issue here: gqty-dev/gqty/issues/276

**Comment by jsimondshiebing** [comment] 2021-11-02 15:13
Thanks Blake! I let our team know the status of this and will continue to monitor this issue as well as the GQty one. Thanks for setting up the repo too as a demo, if you need anything else just let me know.

**Comment by blakewilson** [comment] 2021-11-08 17:05
This issue is actually related to having a conditional within a conditional. This is not supported by GQty. Instead, the selections have to be made before doing anything conditional with the data.

For an example, say you have a `switch` statement looping through block cases:

```tsx
blocks.map((block, index) => {
  switch (block.name) {
    case "core/paragraph": {
      return (
        <div
          key={index}
          dangerouslySetInnerHTML={{
            __html: block?.$on.CoreParagraphBlock?.originalContent,
          }}
        />
      );
    }
  }
});
```

In this instance, the `block?.$on.CoreParagraphBlock?.originalContent` selection is called conditionally behind the `switch` statement. Instead, you would need to first declare the selection, then use it later in the `switch` statement:

```tsx
blocks.map((block, index) => {
  const coreParagraphBlockContent =
    block?.$on.CoreParagraphBlock?.originalContent;

  switch (block.name) {
    case "core/paragraph": {
      return (
        <div
          key={index}
          dangerouslySetInnerHTML={{
            __html: coreParagraphBlockContent,
          }}
        />
      );
    }
  }
});
```

Alternatively, GQty has the [`prepass`](https://gqty.dev/docs/client/helper-functions#prepass) helper function, which allows you to manually specify fields to select, in instances like this.

**Comment by blakewilson** [comment] 2021-11-08 17:08
More context: https://github.com/gqty-dev/gqty/issues/290#issuecomment-962475651

**Comment by jsimondshiebing** [comment] 2021-11-10 19:48
@blakewilson we have made some updates to our code to match the structure above where fields are being specified outside our conditional block switch statement. Since doing that we are able to see content load in server-side consistently so that's a good sign. However it looks as though we have an issue where it's re-rendering the whole page multiple times, header and footer as well which are not handled in the switch statement conditionals, on initial load for some reason causing a flickering effect. We also tried using the prepass helper function but haven't seen a drastic difference in behavior from moving fields outside conditionals.

**Comment by blakewilson** [comment] 2021-11-12 15:04
Hey @jsimondshiebing, awesome! I'm glad that worked.

For the flickering related issue, that sounds more like a rogue `useEffect` that is being called more than needed. I would confirm that there are no unnecessary `useEffect` statements that may be causing this re-rendering.

**Comment by blakewilson** [comment] 2021-11-17 17:04
Hey @jsimondshiebing, wanted to follow up to see if you were able to diagnose this?

**Comment by blakewilson** [comment] 2022-02-01 22:09
Hey @jsimondshiebing, it looks like the original issue here has been resolved, so I'll close this for now. If you experience any other problems though, please feel free to open a new issue

**Closed by blakewilson** 2022-02-01 22:09 UTC
Labels: bug
