### ISSUE TITLE
Bug: Endless refreshing when trying to preview post with different basePath in Next.js config

### ISSUE THREAD

**Issue by riderjensen** [wpengine/faustjs#1287] opened 2023-02-22 23:00 UTC
When adding a `basePath` to `next.config.js` (for example `/blog`), the preview mode gets stuck in an endless authentication loop. 

## Applicable Versions

- `@faustjs/core` version: 0.2.4
- WordPress version: 6.1.1

## Steps To Reproduce

1. Create a base wordpress instance with faust/gql/etc
2. Create a faust project with base config for next.js
3. In the `next.config.js` add a property called `basePath` and set it to `/blog`
4. In wordpress, in your Faust settings, set `Front-end site URL` to reflect the basePath (i.e. `http://localhost:3000/blog`)
5. Attempt to preview one of the posts
6. Note the page never loads and refreshes over and over again with a different code query parameter

Link to code example:

While I don't have a code sample, I can point out the reason this is happening:

1. Observe that the `FAUST_API_BASE_PATH` is hardcoded within the libs [here](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/lib/constants.ts#L1)
2. Observe that the `FAUST_API_BASE_PATH` is imported and used within the router [here](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/server/router/index.ts#L34)
3. Observe that the `FAUST_API_BASE_PATH` is imported and used within the accessToken.ts file [here](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/auth/client/accessToken.ts#L134)
4. Note that there is no way to change this constant in any config 
5. It should be noted that the [docs](https://faustjs.org/docs/next/reference/api-router) for trying to change the `apiBasePath` do not apply here as you can see the [config](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/config/index.ts#L9) takes no parameter for `apiBasePath`
7. [accessToken.ts](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/auth/client/accessToken.ts#L133) is called by [authorize.ts](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/auth/authorize.ts#L47) which is called by [WordPressTemplate](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/components/WordPressTemplate.tsx#L71) on mount.
8. Observe that the `url` in `fetchAccessToken` located in [accessToken.ts](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/auth/client/accessToken.ts#L133)  is made up of constant values that cannot be change but that do also not reference the potential for a Next.js basePath to have been aded.
9. Therefore, even when my base URL is `http://localhost:3000/blog`, accessToken requests will be directed to `http://localhost:3000/api/faust/auth/token` instead of `http://localhost:3000/blog/api/faust/auth/token` which will 404
10. Because `ensureAuthorization` function takes a parameter of redirectUri which is the same location as where we are now, the page essentially refreshes and repeats this over and over.

<img width="1719" alt="Screenshot 2023-02-22 at 12 22 46 PM" src="https://user-images.githubusercontent.com/25038565/220750383-91739697-9816-47a6-ba57-633f5cc35ff6.png">

## The current behavior

The page constantly redirects and 404s over and over again

## The expected behavior

The preview page should load

**Comment by riderjensen** [comment] 2023-02-22 23:16
## Suggested Solution To Above Problem

The constant refreshing is just a symptom, not actually the cause of this issue. The real cause is the `basePath` not being considered in the authorization call our API. Therefore, suggested solution is: Extend [FaustConfig](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/config/index.ts#L9) to include `apiBasePath`. Then when we reference  `FAUST_API_BASE_PATH` in `authorize.ts`, we first get the config and check if `apiBasePath` is set. If it is, we use the user config value. If not, we fallback to the default constant. 

## After Implementing Above Solution Locally:

A second related issue was found. You can see on the [WordPressTemplate.tsx](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/components/WordPressTemplate.tsx#L106) that we check if its a preview and then pull off the url from the parameter `previewPathname`. `previewPathname` is provided from wordpress when you click the "Preview" button the wordpress UI. However, there is no filtering on the Wordpress side from which I can tell. This can be fixed by a string replace but I am not convinced its the best way to continue and I am still investigating potential solution suggestions. Im hopeful this specific issue could be a misconfiguration in WP instead of a Faust issue like the bug listed above

Sample solution for seedQueryUri:
```
        const { basePath } = getConfig();
        seedQueryUri = getQueryParam(window.location.href, 'previewPathname');
        if (basePath) {
          seedQueryUri = seedQueryUri.replace(basePath, '');
        }
```

**Comment by riderjensen** [comment] 2023-02-22 23:31
Ill have an MR open by the end of week with my solution that I will link here. Mostly inspired by the deprecated [core package](https://github.com/wpengine/faustjs/blob/canary/packages/core/src/config/config.ts#L52) (maybe this functionality wasn't migrated on purpose?)

**Comment by theodesp** [comment] 2023-02-23 10:17
Hey @riderjensen. Thank you very much for reporting this. It looks like we didn't port this feature. Any PRs would be welcome.

As for the `previewPathname` I think we need to revisit this piece pf code to see if we can improve it.

**Comment by riderjensen** [comment] 2023-02-23 23:24
@theodesp Thanks for letting me know, I have created a PR.

Another comment that could come up later to hurt the project is that the [router parsedUrl](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/server/router/index.ts#L30) is for the most part undefined. The `req.url` coming in looks like '/api/auth/faust` instead of including `http://example.com`. Not sure if this warrants it's own issue but I thought I would bring it up as its semi-related.

**Comment by blakewilson** [comment] 2023-02-24 17:34
Hey @riderjensen, thanks for the PR, this is great! We'll get this reviewed soon.

As for the `req.url` being relative, this is standard in Next.js/Express, etc. so not much can be done there.

**Comment by theodesp** [comment] 2023-06-16 09:08
Closing this one since it was merged

**Comment by austintreneff** [comment] 2023-06-28 03:43
Hey @theodesp @blakewilson we are still experiencing this issue with previews resulting in an infinite redirect on Faust 1.0.1. It's still trying to authenticate at `/api/faust` instead of `/blog/api/faust` 

I have added the `basePath: '/blog'` to my next.config.js

**Comment by austintreneff** [comment] 2023-06-28 03:59
I am able to reproduce the issue as outlined above, using the faust getting started template @theodesp @blakewilson

**Comment by theodesp** [comment] 2023-06-28 09:36
@austintreneff did you set `apiBasePath` in `faust.config.js as well?
This needs to match the `basePath` parameter.

**Comment by austintreneff** [comment] 2023-06-28 14:53
@theodesp `apiBasePath` [does not seem to be a supported parameter](https://github.com/wpengine/faustjs/blob/deb75b4cfe4df808e043b8244d32cadd1f80442a/packages/faustwp-core/src/config/index.ts#L9) in `faust.config.js`

However, I have tried adding `apiBasePath` to both the `faust.config.js` and the `next.config.js` 

Both my `basePath` and `apiBasePath` are set to `/blog` but the authentication is still trying to authenticate at `/api/faust`

Is there an example of this working I could take a look at?

**Comment by theodesp** [comment] 2023-06-29 12:31
@perrywortman sure. Feel free to submit a PR for this. Thank you.

**Comment by perrywortman** [comment] 2023-06-30 20:50
Hi @theodesp. I was just playing around with the experimental toolbar locally and noticed that the logout feature was 404ing. Seemed related to the basePath issue so I went ahead and prefixed all instances of api routes with the basePath and it fixed this issue as well. It's also possible that [this issue](https://github.com/wpengine/faustjs/issues/1429) might be related and solved by this fix. 

I just updated my PR with the more comprehensive fix [here](https://github.com/wpengine/faustjs/compare/728a43e6d4b249246d7d0b95574a58a2d9875856..1601e73aeca9d59530fa4f0a511b639521c8fc4b) and a new changeset. Let me know what you think - thanks and have a great weekend!

**Comment by perrywortman** [comment] 2023-07-12 14:27
Just checking in on this thread again after a couple of weeks - looks like [my PR](https://github.com/wpengine/faustjs/pull/1479) still needs a review and some of the jobs are failing. Please let me know if there is anything I can do to help push things along.

cc: @theodesp @blakewilson

**Comment by josephfusco** [comment] 2023-08-11 19:03
@riderjensen @perrywortman Thank you for of your work with this! [That PR](https://github.com/wpengine/faustjs/pull/1479) has been merged and is available to test in the latest canary release.

```
npm i @faustwp/core@canary
```

Please let us know if that resolves the original issue!

**Comment by perrywortman** [comment] 2023-08-15 13:58
Thanks! Sounds good @josephfusco - we started testing and will keep you posted sometime today or tomorrow.

**Comment by perrywortman** [comment] 2023-08-16 16:13
Hi @josephfusco 

After testing the Dashlane blog with @faustwp/core@canary and 1.0.3 of the WP plugin, we are seeing 404 errors whenever api routes are hit, e.g. previews. The specific error I see is `unexpected end of json input` from the fetching of the access token in `/auth/client/accessToken.ts`

However, if I manually apply my changes to the latest version @faustwp/core@1.1.0 everything works as expected. Any idea why this 404 might happen only on canary?

**Comment by mindctrl** [comment] 2023-08-17 14:23
@perrywortman thank you for the update. We'll take a closer look.

**Comment by josephfusco** [comment] 2023-08-21 14:22
The endless refreshing [has been patched in canary](https://github.com/wpengine/faustjs/pull/1533/files). Please let us know if that resolves things for you!

```
npm i @faustwp/core@canary
```

**Comment by blakewilson** [comment] 2023-08-21 20:51
Thanks @josephfusco, I was able to confirm this is working as expected with `basePath` specified and using the latest canary version of `@faustwp/core` 🎉 

https://github.com/wpengine/faustjs/assets/5946219/b056631e-8675-42a8-a012-2e4c992885d3

**Comment by perrywortman** [comment] 2023-08-22 16:07
@blakewilson @josephfusco Confirmed working on my end as well. Thank you!

**Closed** 2023-09-01 01:28 UTC
Labels: bug, package: @faustwp/core
