### ISSUE TITLE
Bug: Previews not working on Faustjs.org 

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/faustjs#1738] opened 2024-01-17 17:51 UTC
## Environment
- All packages are loading from Faustjs.org
- Browser, OS, and other relevant software versions: Latest Safari on MacOS

## Description
When clicking "Preview in a new tab" in the post editor the editor loads https://faustjsorg.wpengine.com/wp-admin/undefined in the URL instead of the preview.

<img width="348" alt="Screenshot 2024-01-17 at 11 45 39" src="https://github.com/wpengine/faustjs/assets/394675/2c1b6ab3-8ff6-484e-a365-c066f3ab6791">

## Steps to Reproduce

1. Go to a post edit screen in Faustjs.org
2. Select the "Preview" icon in the toolbar
3. Select "Preview in a new tab"
4. View the NGINX 404 page

## Expected vs. Actual Behavior

Clicking on "preview in a new tab" should open the proper front-end preview in a new browser tab.

**Comment by mindctrl** [comment] 2024-01-18 18:58
Note for whoever picks this up: as Chris was writing this issue, I tested locally and was not able to reproduce. It could be a conflict on the faustjs.org site.

**Comment by theodesp** [comment] 2024-06-27 12:33
Closing since previews seem to work in Faust.org

**Closed by theodesp** 2024-06-27 12:33 UTC
Labels: bug
